name: football_analytics
version: "1.0.0"
config-version: 2
profile: football_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  football_analytics:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  football_analytics:
    +schema: seeds
    team_name_map:
      +column_types:
        api_team_id: integer
        confidence: numeric
