
services:
  db:
    image: postgres:16
    container_name: football-db
    environment:
      POSTGRES_USER: football
      POSTGRES_PASSWORD: football
      POSTGRES_DB: football
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
 
volumes:
  pgdata:
 
